### ISSUE TITLE
fixed_colour 

### ISSUE THREAD

**Issue by jhsoft1** [pjwerdna/PiRGBTree#1]
This is really great!! One little thing: You commented out

# Need to start with something
fixed_colour = random_color()

and therefore I got the error:

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/home/pi/tree/thetree.py", line 162, in run
    self.flicker()
  File "/home/pi/tree/thetree.py", line 242, in flicker
    tree.color = fixed_colour
NameError: name 'fixed_colour' is not defined

**Comment by pjwerdna** [comment]
Noticed this myself a few days after the commit.
